# Generated by Django 5.2.6 on 2025-09-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('ra', models.CharField(max_length=100)),
                ('delim', models.CharField(max_length=200)),
                ('register_voter_2023', models.CharField(max_length=50)),
                ('registered_voter_2024', models.IntegerField()),
                ('pvc_collected', models.IntegerField()),
                ('balance_uncollected', models.IntegerField()),
                ('pvc_45_percent', models.FloatField()),
                ('aa_original', models.FloatField(default=0)),
                ('ad_original', models.FloatField(default=0)),
                ('adc_original', models.FloatField(default=0)),
                ('apc_original', models.FloatField(default=0)),
                ('lp_original', models.FloatField(default=0)),
                ('pdp_original', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sno'],
            },
        ),
        migrations.CreateModel(
            name='VoteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('aa_percentage', models.FloatField(default=0, help_text='Percentage for AA party')),
                ('ad_percentage', models.FloatField(default=0, help_text='Percentage for AD party')),
                ('adc_percentage', models.FloatField(default=0, help_text='Percentage for ADC party')),
                ('apc_percentage', models.FloatField(default=0, help_text='Percentage for APC party')),
                ('lp_percentage', models.FloatField(default=0, help_text='Percentage for LP party')),
                ('pdp_percentage', models.FloatField(default=0, help_text='Percentage for PDP party')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_votes', models.FloatField()),
                ('ad_votes', models.FloatField()),
                ('adc_votes', models.FloatField()),
                ('apc_votes', models.FloatField()),
                ('lp_votes', models.FloatField()),
                ('pdp_votes', models.FloatField()),
                ('total_votes', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pollingunit')),
                ('vote_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voteallocation')),
            ],
            options={
                'unique_together': {('polling_unit', 'vote_allocation')},
            },
        ),
    ]
