# Generated by Django 5.2.4 on 2025-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedresult',
            name='a_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='aac_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='apga_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='apm_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='app_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='bp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='nnpp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='nrm_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='prp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='sdp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='yp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='ypp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedresult',
            name='zlp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='a_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='aac_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='apga_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='apm_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='app_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='bp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='nnpp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='nrm_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='prp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='sdp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='yp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='ypp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='zlp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='a_percentage',
            field=models.FloatField(default=0, help_text='Percentage for Accord party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='aac_percentage',
            field=models.FloatField(default=0, help_text='Percentage for AAC party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='apga_percentage',
            field=models.FloatField(default=0, help_text='Percentage for APGA party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='apm_percentage',
            field=models.FloatField(default=0, help_text='Percentage for APM party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='app_percentage',
            field=models.FloatField(default=0, help_text='Percentage for APP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='bp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for BP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='nnpp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for NNPP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='nrm_percentage',
            field=models.FloatField(default=0, help_text='Percentage for NRM party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='prp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for PRP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='sdp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for SDP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='yp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for YP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='ypp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for YPP party'),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='zlp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for ZLP party'),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='aa_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='ad_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='adc_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='apc_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='lp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='pdp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allocatedresult',
            name='total_votes',
            field=models.FloatField(default=0),
        ),
    ]
