# Generated by Django 5.2.4 on 2025-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allocatedresult_a_votes_allocatedresult_aac_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedresult',
            name='adp_votes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='adp_original',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='voteallocation',
            name='adp_percentage',
            field=models.FloatField(default=0, help_text='Percentage for ADP party'),
        ),
    ]
